image: leonschoorl/clash-ci-image:trusty

.tests:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    TERM: xterm-color
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  cache:
    key: cabal-store-$CI_JOB_NAME
    paths:
      - cabal-store/
  script:
    - export GHC="$CI_JOB_NAME"
    - export THREADS=$(nproc)
    - export CABAL_JOBS=$(nproc)
    - export
    - .ci/setup.sh
    - .ci/build.sh
    - .ci/test.sh

ghc-8.2.2:
  extends: .tests
ghc-8.4.4:
  extends: .tests
ghc-8.6.4:
  extends: .tests

ghc-head:
  # extends: .tests
  allow_failure: true
  script:
    # Awaiting issue: https://github.com/goldfirere/singletons/issues/357
    - echo "GHC head currently disabled, because singletons doesn't build on ghc head"
    - exit 1
